# Generated by Django 5.1.4 on 2024-12-23 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('E_Commerse', '0002_alter_advertisement_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='category_image/'),
        ),
        migrations.AlterField(
            model_name='productpost',
            name='Image',
            field=models.ImageField(blank=True, null=True, upload_to='product_images/'),
        ),
    ]
