# Generated by Django 5.1.4 on 2024-12-25 07:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('E_Commerse', '0005_alter_feedback_rating'),
    ]

    operations = [
        migrations.CreateModel(
            name='usersdata',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('userName', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=8)),
                ('repassword', models.CharField(max_length=8)),
            ],
        ),
        migrations.AlterField(
            model_name='customerprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='E_Commerse.usersdata'),
        ),
    ]
