# Generated by Django 5.1.4 on 2024-12-25 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('E_Commerse', '0007_alter_customerprofile_user_delete_usersdata'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisement',
            name='End_Date',
            field=models.DateTimeField(null=True),
        ),
    ]
