# Generated by Django 5.1.4 on 2024-12-26 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('E_Commerse', '0008_advertisement_end_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='advertisement',
            old_name='Stock',
            new_name='Discount',
        ),
        migrations.RenameField(
            model_name='advertisement',
            old_name='Description',
            new_name='Slogan',
        ),
        migrations.RemoveField(
            model_name='advertisement',
            name='Price',
        ),
    ]
