# Generated by Django 5.1.4 on 2024-12-26 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('E_Commerse', '0009_rename_stock_advertisement_discount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='Quantity',
            field=models.IntegerField(default=1),
        ),
    ]
