# Generated by Django 5.1.4 on 2024-12-27 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('E_Commerse', '0011_address'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Address',
        ),
    ]
