# Generated by Django 5.1.4 on 2024-12-27 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('E_Commerse', '0013_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='Customer',
        ),
        migrations.DeleteModel(
            name='OrderItems',
        ),
        migrations.DeleteModel(
            name='Orders',
        ),
    ]
