# Generated by Django 5.1.4 on 2024-12-28 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('E_Commerse', '0017_orders_orderitems'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='Customer',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='order_address',
        ),
        migrations.DeleteModel(
            name='OrderItems',
        ),
        migrations.DeleteModel(
            name='Orders',
        ),
    ]
