# Generated by Django 5.1.4 on 2024-12-29 05:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('E_Commerse', '0021_address_order_orderitem_payment_order_payment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='order',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='order',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='product',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
        migrations.DeleteModel(
            name='OrderItem',
        ),
    ]
