# Generated by Django 5.1.4 on 2025-01-01 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('E_Commerse', '0026_alter_customerprofile_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerprofile',
            name='Email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='customerprofile',
            name='First_Name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='customerprofile',
            name='Gender',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='customerprofile',
            name='Last_Name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='customerprofile',
            name='Phone_Number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
